// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TpaSodManagement.Data;

#nullable disable

namespace TpaSodManagement.Data.Migrations.Identity
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102121102_OrganizationNameToOrganizationId")]
    partial class OrganizationNameToOrganizationId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PrimaryContact")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("WebsiteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.AreaType", b =>
                {
                    b.Property<int>("AreaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaTypeId"));

                    b.Property<string>("AreaTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConversionToSquareMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UnitAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaTypeId");

                    b.ToTable("AreaType");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Certificate", b =>
                {
                    b.Property<long>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CertificateId"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateRangeEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateRangeStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CertificateTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DigitalSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuingOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RelatedSaleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelatedSeedingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelatedWasteId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificateId");

                    b.HasIndex("CertificateTypeId");

                    b.HasIndex("FarmId");

                    b.HasIndex("RelatedSaleId");

                    b.HasIndex("RelatedSeedingId");

                    b.HasIndex("RelatedWasteId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.CertificateType", b =>
                {
                    b.Property<int>("CertificateTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateTypeId"));

                    b.Property<string>("CertificateTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresRenewal")
                        .HasColumnType("bit");

                    b.Property<int?>("ValidityPeriodDays")
                        .HasColumnType("int");

                    b.HasKey("CertificateTypeId");

                    b.ToTable("CertificateType");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CustomerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Farm", b =>
                {
                    b.Property<long>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FarmId"));

                    b.Property<int?>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CertificationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClimateZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ElevationMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IrrigationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("OrganicCertified")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("SoilType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalArea")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FarmId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Farm");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Field", b =>
                {
                    b.Property<long>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FieldId"));

                    b.Property<decimal>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("BoundaryCoordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IrrigationAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SlopePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoilType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("FarmId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Organization", b =>
                {
                    b.Property<long>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrganizationId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("LogoBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OrganizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonId"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<int?>("CertificateTypeId")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresCertificate")
                        .HasColumnType("bit");

                    b.Property<decimal?>("StandardPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CertificateTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Sale", b =>
                {
                    b.Property<long>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("SaleId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FarmId");

                    b.HasIndex("SaleTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleLineItem", b =>
                {
                    b.Property<long>("SaleLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleLineItemId"));

                    b.Property<decimal?>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("CertificateSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<long?>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoyaltyInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SeedingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TagRangeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SaleLineItemId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("FieldId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SeedingId");

                    b.HasIndex("TagRangeId");

                    b.ToTable("SaleLineItem");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleType", b =>
                {
                    b.Property<int>("SaleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleTypeId"));

                    b.Property<int?>("CertificateTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresCertificate")
                        .HasColumnType("bit");

                    b.Property<string>("SaleTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TaxApplicable")
                        .HasColumnType("bit");

                    b.HasKey("SaleTypeId");

                    b.HasIndex("CertificateTypeId");

                    b.ToTable("SaleType");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Seeding", b =>
                {
                    b.Property<long>("SeedingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeedingId"));

                    b.Property<decimal>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SeedRatePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("SeedingDate")
                        .HasColumnType("date");

                    b.Property<string>("SeedingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoilMoisture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoilTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TagRangeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeatherConditions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeedingId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FieldId");

                    b.HasIndex("TagRangeId");

                    b.HasIndex("UserId");

                    b.ToTable("Seeding");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusOrder")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.TagRange", b =>
                {
                    b.Property<long>("TagRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagRangeId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("TagEndNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("TagPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagRangeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TagStartNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("TagSuffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTags")
                        .HasColumnType("int");

                    b.HasKey("TagRangeId");

                    b.ToTable("TagRange");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Testimonial", b =>
                {
                    b.Property<long>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TestimonialId"));

                    b.Property<long?>("ApprovedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ApprovedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("Improvements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhotoReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemsToSolve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TestimonialTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WouldRecommend")
                        .HasColumnType("bit");

                    b.HasKey("TestimonialId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FarmId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StatusId");

                    b.ToTable("Testimonial");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Waste", b =>
                {
                    b.Property<long>("WasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WasteId"));

                    b.Property<decimal>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("DisposalLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisposalMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnvironmentalImpactAssessed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EstimatedLossValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RegulatoryReported")
                        .HasColumnType("bit");

                    b.Property<long?>("SeedingId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("WasteDate")
                        .HasColumnType("date");

                    b.Property<int>("WasteReasonId")
                        .HasColumnType("int");

                    b.HasKey("WasteId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FieldId");

                    b.HasIndex("SeedingId");

                    b.HasIndex("UserId");

                    b.HasIndex("WasteReasonId");

                    b.ToTable("Waste");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteCertificate", b =>
                {
                    b.Property<long>("WasteCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WasteCertificateId"));

                    b.Property<long>("CertificateId")
                        .HasColumnType("bigint");

                    b.Property<long>("CertificateNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WasteId")
                        .HasColumnType("bigint");

                    b.HasKey("WasteCertificateId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("WasteId");

                    b.ToTable("WasteCertificate");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteReason", b =>
                {
                    b.Property<int>("WasteReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WasteReasonId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WasteReasonId");

                    b.ToTable("WasteReason");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PermissionName");

                    b.HasKey("Id")
                        .HasName("PK_Permission");

                    b.HasIndex(new[] { "Name" }, "UK_Permission_Name")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("TpaSodManagement.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolePermissionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_RolePermission");

                    b.HasIndex("PermissionId");

                    b.HasIndex(new[] { "RoleId", "PermissionId" }, "UK_RolePermission_RolePermission")
                        .IsUnique();

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Farm", null)
                        .WithMany("TpaUsers")
                        .HasForeignKey("FarmId");

                    b.HasOne("TpaSodManagement.Models.Db.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AspNetUsers_Organizations");

                    b.HasOne("TpaSodManagement.Models.Db.Person", null)
                        .WithOne("TpaUser")
                        .HasForeignKey("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "PersonId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Certificate", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.CertificateType", "CertificateType")
                        .WithMany("Certificates")
                        .HasForeignKey("CertificateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Certificates")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Sale", "RelatedSale")
                        .WithMany("Certificates")
                        .HasForeignKey("RelatedSaleId");

                    b.HasOne("TpaSodManagement.Models.Db.Seeding", "RelatedSeeding")
                        .WithMany("Certificates")
                        .HasForeignKey("RelatedSeedingId");

                    b.HasOne("TpaSodManagement.Models.Db.Waste", "RelatedWaste")
                        .WithMany("Certificates")
                        .HasForeignKey("RelatedWasteId");

                    b.HasOne("TpaSodManagement.Models.Db.Status", "Status")
                        .WithMany("Certificates")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateType");

                    b.Navigation("Farm");

                    b.Navigation("RelatedSale");

                    b.Navigation("RelatedSeeding");

                    b.Navigation("RelatedWaste");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Customer", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Organization", "Organization")
                        .WithMany("Customers")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("TpaSodManagement.Models.Db.Person", "Person")
                        .WithMany("Customers")
                        .HasForeignKey("PersonId");

                    b.Navigation("Organization");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Farm", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Farms")
                        .HasForeignKey("AreaTypeId");

                    b.HasOne("TpaSodManagement.Models.Db.Organization", "Organization")
                        .WithMany("Farms")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Field", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Fields")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Fields")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Product", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.CertificateType", "CertificateType")
                        .WithMany("Products")
                        .HasForeignKey("CertificateTypeId");

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Currency", "Currency")
                        .WithMany("Products")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("TpaSodManagement.Models.Db.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Currency");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Sale", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Currency", "Currency")
                        .WithMany("Sales")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Sales")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.SaleType", "SaleType")
                        .WithMany("Sales")
                        .HasForeignKey("SaleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Status", "Status")
                        .WithMany("Sales")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("Farm");

                    b.Navigation("SaleType");

                    b.Navigation("Status");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleLineItem", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("AreaTypeId");

                    b.HasOne("TpaSodManagement.Models.Db.Field", "Field")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("FieldId");

                    b.HasOne("TpaSodManagement.Models.Db.Product", "Product")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Sale", "Sale")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Seeding", "Seeding")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("SeedingId");

                    b.HasOne("TpaSodManagement.Models.Db.TagRange", "TagRange")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("TagRangeId");

                    b.Navigation("AreaType");

                    b.Navigation("Field");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("Seeding");

                    b.Navigation("TagRange");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleType", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.CertificateType", "CertificateType")
                        .WithMany("SaleTypes")
                        .HasForeignKey("CertificateTypeId");

                    b.Navigation("CertificateType");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Seeding", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Seedings")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Seedings")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Field", "Field")
                        .WithMany("Seedings")
                        .HasForeignKey("FieldId");

                    b.HasOne("TpaSodManagement.Models.Db.TagRange", "TagRange")
                        .WithMany("Seedings")
                        .HasForeignKey("TagRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("TagRange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Testimonial", b =>
                {
                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("TpaSodManagement.Models.Db.Customer", "Customer")
                        .WithMany("Testimonials")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Testimonials")
                        .HasForeignKey("FarmId");

                    b.HasOne("TpaSodManagement.Models.Db.Person", "Person")
                        .WithMany("Testimonials")
                        .HasForeignKey("PersonId");

                    b.HasOne("TpaSodManagement.Models.Db.Status", "Status")
                        .WithMany("Testimonials")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Farm");

                    b.Navigation("Person");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Waste", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Wastes")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Currency", "Currency")
                        .WithMany("Wastes")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Wastes")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Field", "Field")
                        .WithMany("Wastes")
                        .HasForeignKey("FieldId");

                    b.HasOne("TpaSodManagement.Models.Db.Seeding", "Seeding")
                        .WithMany("Wastes")
                        .HasForeignKey("SeedingId");

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.WasteReason", "WasteReason")
                        .WithMany("Wastes")
                        .HasForeignKey("WasteReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Currency");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("Seeding");

                    b.Navigation("User");

                    b.Navigation("WasteReason");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteCertificate", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Certificate", "Certificate")
                        .WithMany("WasteCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Waste", "Waste")
                        .WithMany("WasteCertificates")
                        .HasForeignKey("WasteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("Waste");
                });

            modelBuilder.Entity("TpaSodManagement.Models.RolePermission", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permission");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.AreaType", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Fields");

                    b.Navigation("SaleLineItems");

                    b.Navigation("Seedings");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Certificate", b =>
                {
                    b.Navigation("WasteCertificates");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.CertificateType", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Products");

                    b.Navigation("SaleTypes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Currency", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Sales");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Customer", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Farm", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Fields");

                    b.Navigation("Sales");

                    b.Navigation("Seedings");

                    b.Navigation("Testimonials");

                    b.Navigation("TpaUsers");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Field", b =>
                {
                    b.Navigation("SaleLineItems");

                    b.Navigation("Seedings");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Organization", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Farms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Person", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Testimonials");

                    b.Navigation("TpaUser");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Product", b =>
                {
                    b.Navigation("SaleLineItems");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Sale", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("SaleLineItems");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleType", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Seeding", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("SaleLineItems");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Status", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Sales");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.TagRange", b =>
                {
                    b.Navigation("SaleLineItems");

                    b.Navigation("Seedings");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Waste", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("WasteCertificates");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteReason", b =>
                {
                    b.Navigation("Wastes");
                });
#pragma warning restore 612, 618
        }
    }
}
