// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TpaSodManagement.Models.Db;

#nullable disable

namespace TpaSodManagement.Data.Migrations.Sod
{
    [DbContext(typeof(SodDbContext))]
    partial class SodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<long?>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WebsiteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.HasIndex("FarmId");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.HasIndex("WebsiteId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AddressId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddressTypeId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("VerificationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("StateProvinceId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.AddressType", b =>
                {
                    b.Property<int>("AddressTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressTypeId"));

                    b.Property<string>("AddressTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AddressTypeId");

                    b.ToTable("AddressTypes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.AreaType", b =>
                {
                    b.Property<int>("AreaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaTypeId"));

                    b.Property<string>("AreaTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConversionToSquareMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UnitAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaTypeId");

                    b.ToTable("AreaTypes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Certificate", b =>
                {
                    b.Property<long>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CertificateId"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateRangeEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateRangeStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CertificateTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DigitalSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuingOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RelatedSaleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelatedSeedingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelatedWasteId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WasteId")
                        .HasColumnType("bigint");

                    b.HasKey("CertificateId");

                    b.HasIndex("CertificateTypeId");

                    b.HasIndex("FarmId");

                    b.HasIndex("RelatedSaleId");

                    b.HasIndex("RelatedSeedingId");

                    b.HasIndex("RelatedWasteId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.HasIndex("WasteId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.CertificateType", b =>
                {
                    b.Property<int>("CertificateTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateTypeId"));

                    b.Property<string>("CertificateTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresRenewal")
                        .HasColumnType("bit");

                    b.Property<int?>("ValidityPeriodDays")
                        .HasColumnType("int");

                    b.HasKey("CertificateTypeId");

                    b.ToTable("CertificateTypes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhonePrefix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CustomerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Farm", b =>
                {
                    b.Property<long>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FarmId"));

                    b.Property<int?>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CertificationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClimateZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ElevationMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IrrigationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("OrganicCertified")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("SoilType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalArea")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FarmId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Field", b =>
                {
                    b.Property<long>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FieldId"));

                    b.Property<decimal>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("BoundaryCoordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IrrigationAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SlopePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoilType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("FarmId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Organization", b =>
                {
                    b.Property<long>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrganizationId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("LogoBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OrganizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonId"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<int?>("CertificateTypeId")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresCertificate")
                        .HasColumnType("bit");

                    b.Property<decimal?>("StandardPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CertificateTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Sale", b =>
                {
                    b.Property<long>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("SaleId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FarmId");

                    b.HasIndex("SaleTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleLineItem", b =>
                {
                    b.Property<long>("SaleLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleLineItemId"));

                    b.Property<decimal?>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("CertificateSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<long?>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoyaltyInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SeedingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TagRangeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SaleLineItemId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("FieldId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SeedingId");

                    b.HasIndex("TagRangeId");

                    b.ToTable("SaleLineItems");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleType", b =>
                {
                    b.Property<int>("SaleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleTypeId"));

                    b.Property<int?>("CertificateTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresCertificate")
                        .HasColumnType("bit");

                    b.Property<string>("SaleTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TaxApplicable")
                        .HasColumnType("bit");

                    b.HasKey("SaleTypeId");

                    b.HasIndex("CertificateTypeId");

                    b.ToTable("SaleTypes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Seeding", b =>
                {
                    b.Property<long>("SeedingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeedingId"));

                    b.Property<decimal>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SeedRatePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("SeedingDate")
                        .HasColumnType("date");

                    b.Property<string>("SeedingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoilMoisture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoilTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TagRangeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeatherConditions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeedingId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FieldId");

                    b.HasIndex("TagRangeId");

                    b.HasIndex("UserId");

                    b.ToTable("Seedings");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.StateProvince", b =>
                {
                    b.Property<int>("StateProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("StateProvinces");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusOrder")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.TagRange", b =>
                {
                    b.Property<long>("TagRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagRangeId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("TagEndNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("TagPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagRangeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TagStartNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("TagSuffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTags")
                        .HasColumnType("int");

                    b.HasKey("TagRangeId");

                    b.ToTable("TagRanges");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Testimonial", b =>
                {
                    b.Property<long>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TestimonialId"));

                    b.Property<long?>("ApprovedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ApprovedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("Improvements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhotoReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemsToSolve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TestimonialTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WouldRecommend")
                        .HasColumnType("bit");

                    b.HasKey("TestimonialId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FarmId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StatusId");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Waste", b =>
                {
                    b.Property<long>("WasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WasteId"));

                    b.Property<decimal>("AreaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("DisposalLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisposalMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnvironmentalImpactAssessed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EstimatedLossValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RegulatoryReported")
                        .HasColumnType("bit");

                    b.Property<long?>("SeedingId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("WasteDate")
                        .HasColumnType("date");

                    b.Property<int>("WasteReasonId")
                        .HasColumnType("int");

                    b.HasKey("WasteId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FieldId");

                    b.HasIndex("SeedingId");

                    b.HasIndex("UserId");

                    b.HasIndex("WasteReasonId");

                    b.ToTable("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteCertificate", b =>
                {
                    b.Property<long>("WasteCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("WasteCertificateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WasteCertificateId"));

                    b.Property<long>("CertificateId")
                        .HasColumnType("bigint")
                        .HasColumnName("CertificateId");

                    b.Property<long>("CertificateNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("CertificateNumber");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<long>("WasteId")
                        .HasColumnType("bigint")
                        .HasColumnName("WasteId");

                    b.HasKey("WasteCertificateId")
                        .HasName("PK_WasteCertificate");

                    b.HasIndex("CertificateId");

                    b.HasIndex("WasteId");

                    b.ToTable("WasteCertificate", (string)null);
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteReason", b =>
                {
                    b.Property<int>("WasteReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WasteReasonId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WasteReasonId");

                    b.ToTable("WasteReasons");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Website", b =>
                {
                    b.Property<long>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WebsiteId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WebsiteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebsiteId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Address", null)
                        .WithOne("TpaUser")
                        .HasForeignKey("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "AddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TpaSodManagement.Models.Db.Farm", null)
                        .WithMany("TpaUsers")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TpaSodManagement.Models.Db.Person", null)
                        .WithOne("TpaUser")
                        .HasForeignKey("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "PersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TpaSodManagement.Models.Db.Website", null)
                        .WithMany("TpaUsers")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Address", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AddressType", "AddressType")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.StateProvince", "StateProvince")
                        .WithMany("Addresses")
                        .HasForeignKey("StateProvinceId");

                    b.Navigation("AddressType");

                    b.Navigation("StateProvince");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Certificate", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.CertificateType", "CertificateType")
                        .WithMany("Certificates")
                        .HasForeignKey("CertificateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Certificates")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Sale", "RelatedSale")
                        .WithMany("Certificates")
                        .HasForeignKey("RelatedSaleId");

                    b.HasOne("TpaSodManagement.Models.Db.Seeding", "RelatedSeeding")
                        .WithMany("Certificates")
                        .HasForeignKey("RelatedSeedingId");

                    b.HasOne("TpaSodManagement.Models.Db.Waste", "RelatedWaste")
                        .WithMany()
                        .HasForeignKey("RelatedWasteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Certificate_Waste");

                    b.HasOne("TpaSodManagement.Models.Db.Status", "Status")
                        .WithMany("Certificates")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Certificate_TpaSodManagementUser");

                    b.HasOne("TpaSodManagement.Models.Db.Waste", null)
                        .WithMany("Certificates")
                        .HasForeignKey("WasteId");

                    b.Navigation("CertificateType");

                    b.Navigation("Farm");

                    b.Navigation("RelatedSale");

                    b.Navigation("RelatedSeeding");

                    b.Navigation("RelatedWaste");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Customer", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Organization", "Organization")
                        .WithMany("Customers")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("TpaSodManagement.Models.Db.Person", "Person")
                        .WithMany("Customers")
                        .HasForeignKey("PersonId");

                    b.Navigation("Organization");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Farm", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Farms")
                        .HasForeignKey("AreaTypeId");

                    b.HasOne("TpaSodManagement.Models.Db.Organization", "Organization")
                        .WithMany("Farms")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Field", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Fields")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Fields")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Product", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.CertificateType", "CertificateType")
                        .WithMany("Products")
                        .HasForeignKey("CertificateTypeId");

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Product_TpaSodManagementUser_CreatedBy");

                    b.HasOne("TpaSodManagement.Models.Db.Currency", "Currency")
                        .WithMany("Products")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("TpaSodManagement.Models.Db.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Currency");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Sale", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Currency", "Currency")
                        .WithMany("Sales")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Sales")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.SaleType", "SaleType")
                        .WithMany("Sales")
                        .HasForeignKey("SaleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Status", "Status")
                        .WithMany("Sales")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sale_TpaSodManagementUser_UpdatedBy");

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sale_TpaSodManagementUser");

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("Farm");

                    b.Navigation("SaleType");

                    b.Navigation("Status");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleLineItem", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("AreaTypeId");

                    b.HasOne("TpaSodManagement.Models.Db.Field", "Field")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("FieldId");

                    b.HasOne("TpaSodManagement.Models.Db.Product", "Product")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Sale", "Sale")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Seeding", "Seeding")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("SeedingId");

                    b.HasOne("TpaSodManagement.Models.Db.TagRange", "TagRange")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("TagRangeId");

                    b.Navigation("AreaType");

                    b.Navigation("Field");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("Seeding");

                    b.Navigation("TagRange");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleType", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.CertificateType", "CertificateType")
                        .WithMany("SaleTypes")
                        .HasForeignKey("CertificateTypeId");

                    b.Navigation("CertificateType");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Seeding", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Seedings")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Seedings")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Field", "Field")
                        .WithMany("Seedings")
                        .HasForeignKey("FieldId");

                    b.HasOne("TpaSodManagement.Models.Db.TagRange", "TagRange")
                        .WithMany("Seedings")
                        .HasForeignKey("TagRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Seeding_TpaSodManagementUser");

                    b.Navigation("AreaType");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("TagRange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.StateProvince", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Country", "Country")
                        .WithMany("StateProvinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Testimonial", b =>
                {
                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Testimonial_TpaSodManagementUser_ApprovedBy");

                    b.HasOne("TpaSodManagement.Models.Db.Customer", "Customer")
                        .WithMany("Testimonials")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Testimonials")
                        .HasForeignKey("FarmId");

                    b.HasOne("TpaSodManagement.Models.Db.Person", "Person")
                        .WithMany("Testimonials")
                        .HasForeignKey("PersonId");

                    b.HasOne("TpaSodManagement.Models.Db.Status", "Status")
                        .WithMany("Testimonials")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Farm");

                    b.Navigation("Person");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Waste", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.AreaType", "AreaType")
                        .WithMany("Wastes")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Currency", "Currency")
                        .WithMany("Wastes")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("TpaSodManagement.Models.Db.Farm", "Farm")
                        .WithMany("Wastes")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpaSodManagement.Models.Db.Field", "Field")
                        .WithMany("Wastes")
                        .HasForeignKey("FieldId");

                    b.HasOne("TpaSodManagement.Models.Db.Seeding", "Seeding")
                        .WithMany("Wastes")
                        .HasForeignKey("SeedingId");

                    b.HasOne("TpaSodManagement.Areas.Identity.Data.TpaSodManagementUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Waste_TpaSodManagementUser");

                    b.HasOne("TpaSodManagement.Models.Db.WasteReason", "WasteReason")
                        .WithMany("Wastes")
                        .HasForeignKey("WasteReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Currency");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("Seeding");

                    b.Navigation("User");

                    b.Navigation("WasteReason");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteCertificate", b =>
                {
                    b.HasOne("TpaSodManagement.Models.Db.Certificate", "Certificate")
                        .WithMany("WasteCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_WasteCertificate_Certificate");

                    b.HasOne("TpaSodManagement.Models.Db.Waste", "Waste")
                        .WithMany("WasteCertificates")
                        .HasForeignKey("WasteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_WasteCertificate_waste");

                    b.Navigation("Certificate");

                    b.Navigation("Waste");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Address", b =>
                {
                    b.Navigation("TpaUser");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.AddressType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.AreaType", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Fields");

                    b.Navigation("SaleLineItems");

                    b.Navigation("Seedings");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Certificate", b =>
                {
                    b.Navigation("WasteCertificates");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.CertificateType", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Products");

                    b.Navigation("SaleTypes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Country", b =>
                {
                    b.Navigation("StateProvinces");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Currency", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Sales");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Customer", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Farm", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Fields");

                    b.Navigation("Sales");

                    b.Navigation("Seedings");

                    b.Navigation("Testimonials");

                    b.Navigation("TpaUsers");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Field", b =>
                {
                    b.Navigation("SaleLineItems");

                    b.Navigation("Seedings");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Organization", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Farms");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Person", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Testimonials");

                    b.Navigation("TpaUser");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Product", b =>
                {
                    b.Navigation("SaleLineItems");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Sale", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("SaleLineItems");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.SaleType", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Seeding", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("SaleLineItems");

                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.StateProvince", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Status", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Sales");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.TagRange", b =>
                {
                    b.Navigation("SaleLineItems");

                    b.Navigation("Seedings");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Waste", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("WasteCertificates");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.WasteReason", b =>
                {
                    b.Navigation("Wastes");
                });

            modelBuilder.Entity("TpaSodManagement.Models.Db.Website", b =>
                {
                    b.Navigation("TpaUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
